# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 880c9d8153a6553b7021fde23f3bcbb13026c6631dbe819f0449fc33410aece7aef18814d5a8a6fd69889e993b5115a07f06729496e19ba77d8ced1ccdfd706a

test:
  secret_key_base: e0d42ae2893b3b2561deca279811aa02926dd83f88a5362739dd5baef2bfa910647e26789e3d3b3237fbfcc9dcf204ec48e836bca10d4529d309ed2c009b529e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
